apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}-operator
  labels:
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.operator.type }}
  selector:
  {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.operator.ports | toYaml | nindent 2 -}}
