account:
  serviceAccount:
    annotations: {}
defectDojoApiCredentials:
  apiKey: ""
  url: ""
kubernetesClusterDomain: cluster.local
operator:
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: metrics
  replicas: 1
  trivyDojoReportOperator:
    env:
      defectDojoActive: "true"
      defectDojoAutoCreateContext: "true"
      defectDojoCloseOldFindings: "false"
      defectDojoCloseOldFindingsProductScope: "false"
      defectDojoDeduplicationOnEngagement: "true"
      defectDojoDoNotReactivate: "true"
      defectDojoEngagementName: engagement
      defectDojoEvalEngagementName: "false"
      defectDojoEvalProductName: "false"
      defectDojoEvalProductTypeName: "false"
      defectDojoEvalTestTitle: "false"
      defectDojoMinimumSeverity: Info
      defectDojoProductName: product
      defectDojoProductTypeName: Research and Development
      defectDojoPushToJira: "false"
      defectDojoTestTitle: Kubernetes
      defectDojoVerified: "false"
      reports: vulnerabilityreports
    image:
      repository: ghcr.io/telekom-mms/docker-trivy-dojo-operator
      tag: 0.5.2@sha256:a20198f383a1cdd0dde900241dba0cbfbbccbb5f039ea2ee70f2186650fe34de
  type: ClusterIP
