account:
  serviceAccount:
    annotations: {}
defectDojoApiCredentials:
  apiKey: ""
  url: ""
kubernetesClusterDomain: cluster.local
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
operator:
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: metrics
  replicas: 1
  trivyDojoReportOperator:
    env:
      defectDojoActive: "true"
      defectDojoAutoCreateContext: "true"
      defectDojoCloseOldFindings: "false"
      defectDojoCloseOldFindingsProductScope: "false"
      defectDojoDeduplicationOnEngagement: "true"
      defectDojoDoNotReactivate: "true"
      defectDojoEngagementName: engagement
      defectDojoEvalEngagementName: "false"
      defectDojoEvalProductName: "false"
      defectDojoEvalProductTypeName: "false"
      defectDojoEvalEnvName: "false"
      defectDojoEvalTestTitle: "false"
      defectDojoMinimumSeverity: Info
      defectDojoProductName: product
      defectDojoProductTypeName: Research and Development
      defectDojoEnvName: Development
      defectDojoPushToJira: "false"
      defectDojoTestTitle: Kubernetes
      defectDojoVerified: "false"
      reports: vulnerabilityreports
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
    image:
      repository: ghcr.io/telekom-mms/docker-trivy-dojo-operator
      tag: 0.5.7
  type: ClusterIP
