name: Hadolint
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: Hadolint-your-PR
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
