name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3

      - name: Install Chart Releaser
        run: |
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz | tar xz
          sudo mv cr /usr/local/bin/

      - name: Get the version tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Package and Release Charts
        run: |
          cr package charts/
          gh release upload $VERSION_TAG .cr-release-packages/trivy-dojo-report-operator-$VERSION_TAG.tgz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Branch gh-pages
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: gh-pages

      - name: Update index.yaml
        run: cr index -o telekom-mms -r trivy-dojo-report-operator -c -i index.yaml --token ${{ secrets.GITHUB_TOKEN }}

      - name: Push Updated index.yaml
        uses: github-actions-x/commit@722d56b8968bf00ced78407bbe2ead81062d8baa # v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: gh-pages
          commit-message: Update version to $VERSION_TAG
          force-add: 'true'
          files: index.yaml
          name: Deutsche Telekom MMS
          email: mms@telekom.de
